name: Build

on:
    push:
    workflow_dispatch:

jobs:
    build:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@main

            - name: Cache Theos
              id: theosCache
              uses: actions/cache@main
              with:
                  path: theos
                  key: theos

            - name: Checkout theos/theos
              if: steps.theosCache.outputs.cache-hit != 'true'
              uses: actions/checkout@main
              with:
                  repository: theos/theos
                  ref: master
                  submodules: recursive
                  path: theos

            - name: Checkout theos/sdks
              if: steps.theosCache.outputs.cache-hit != 'true'
              uses: actions/checkout@main
              with:
                  repository: theos/sdks
                  path: theos/sdks

            - name: Install Build Dependencies
              run: |
                  brew list make >/dev/null 2>&1 || brew install make
                  brew list xz >/dev/null 2>&1 || brew install xz
                  brew list ldid >/dev/null 2>&1 || brew install ldid

            - name: Extract Name from Control File
              id: name
              run: |
                  NAME=$(grep '^Name:' control | cut -d ' ' -f 2)
                  echo "NAME=$NAME" >> "$GITHUB_OUTPUT"

            - name: Extract Version from Control File
              id: version
              run: |
                  VERSION=$(grep '^Version:' control | cut -d ' ' -f 2)
                  echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

            - name: Build Package
              run: |
                  export THEOS=theos
                  gmake clean package FINALPACKAGE=1
                  gmake clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

            - name: Upload Build Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ steps.name.outputs.NAME }}_v${{ steps.version.outputs.VERSION }}
                  path: packages/*.deb

            - name: Create GitHub Release
              uses: actions/create-release@v1
              with:
                  tag_name: v${{ steps.version.outputs.version }}
                  release_name: Release v${{ steps.version.outputs.version }}
                  body: |
                      This release includes:
                      - Artifacts built from the latest workflow.
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
